# Generated by Django 4.0.1 on 2022-06-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenbookEventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.BooleanField(default=False)),
                ('advance_quotation', models.IntegerField()),
                ('venue_event_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venbookeventinfo')),
            ],
        ),
    ]
