# Generated by Django 4.0.1 on 2022-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venbookeventrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venbookeventrequest',
            name='advance_quotation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venbookeventrequest',
            name='request_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
