# Generated by Django 4.0.1 on 2022-06-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_venbookeventrequest_advance_quotation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venbookeventrequest',
            old_name='request_status',
            new_name='accept',
        ),
        migrations.AddField(
            model_name='venbookeventrequest',
            name='reject',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='venbookeventrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
