# Generated by Django 4.0.1 on 2022-06-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_request_status_venbookeventrequest_accept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='canceledVenbookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainingDays', models.CharField(max_length=155)),
                ('eventRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venbookeventrequest')),
            ],
        ),
    ]
