# Generated by Django 4.0.1 on 2022-06-14 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_canceledvenbookrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledvenbookrequest',
            name='eventRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.venbookeventrequest'),
        ),
    ]
