# Generated by Django 4.0.1 on 2022-06-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_venbookeventrequest_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='venbookeventrequest',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='canceledVenbookRequest',
        ),
    ]
