# Generated by Django 4.0.1 on 2022-06-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_venbookeventrequest_payment_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venbookeventrequest',
            old_name='payment_completed',
            new_name='advance_payment_received',
        ),
        migrations.AddField(
            model_name='venbookeventrequest',
            name='advance_payment_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
