# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='is_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('unverified', models.BooleanField(default=False)),
                ('unverified_msg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VenueAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=255)),
                ('pan', models.CharField(max_length=155)),
                ('city', models.CharField(default='Kathmandu', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('capacity', models.CharField(max_length=155)),
                ('owner_citizenship', models.ImageField(default='default.jpg', upload_to='owner_citizenship')),
                ('venue_pp', models.ImageField(default='default.jpg', upload_to='venue_pp')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images')),
                ('venue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.venueaccount')),
            ],
        ),
    ]
