# Generated by Django 4.0.1 on 2022-06-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_venueaccount_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueaccount',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venueaccount',
            name='lon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
