# Generated by Django 4.0.1 on 2022-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_venueaccount_lat_venueaccount_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueaccount',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venueaccount',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
