# Generated by Django 4.0.1 on 2022-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_venueaccount_lat_alter_venueaccount_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
