# Generated by Django 4.0.1 on 2022-06-15 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_rename_payment_completed_venbookeventrequest_advance_payment_received_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePaymentSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti')], max_length=150)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venbookeventrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvancePaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti')], max_length=150)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('booking_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venbookeventrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
