# Generated by Django 4.0.1 on 2022-06-15 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_payment_completed_venbookeventrequest_advance_payment_received_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvancePaymentReceived',
            new_name='AdvancePaymentReceived_Log',
        ),
        migrations.RenameModel(
            old_name='AdvancePaymentSent',
            new_name='AdvancePaymentSent_Log',
        ),
    ]
