# Generated by Django 4.0.4 on 2022-06-02 16:02

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenuePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_people', models.IntegerField(blank=True, null=True)),
                ('mid_people', models.IntegerField(blank=True, null=True)),
                ('max_people', models.IntegerField(blank=True, null=True)),
                ('dj_price', models.IntegerField(blank=True, null=True)),
                ('decoration', models.BooleanField(blank=True, default=False, null=True)),
                ('projectors', models.IntegerField(blank=True, null=True)),
                ('venue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.venueaccount')),
            ],
        ),
        migrations.CreateModel(
            name='VenueFacilitiesServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', multiselectfield.db.fields.MultiSelectField(choices=[('DJ Service', 'DJ Service'), ('Parking Space', 'Parking Space'), ('Customized decoration', 'Customized decoration'), ('Projectors', 'Projectors'), ('Changing Room', 'Changing Room'), ('Makeup Service', 'Makeup Service'), ('Fireworks', 'Fireworks'), ('Live Music', 'Live Music')], max_length=107)),
                ('venue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.venueaccount')),
            ],
        ),
    ]
