# Generated by Django 4.0.1 on 2022-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
    ]
